language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_install:
 - pear install pear.php.net/PHP_CodeSniffer
 - pear install pear.phpdoc.org/phpdocumentor
 - pear install pear.phpunit.de/phpcpd
 - pear install pear.phpunit.de/phploc
 - pear install pear.pdepend.org/pdepend
 - pear install pear.phpmd.org/php_pmd
 - phpenv rehash
 
script:
 - ant run-tests

notifications:
  email: tw@techdivision.com